### ISSUE TITLE
Bug: Maitreya 8 (beta 3) calculations are slow

### ISSUE THREAD

**Issue by ossiviljakainen** [martin-pe/maitreya8#13]
When casting a new chart or when changing tab in multiple views, the program is not very responsive but reacts slowly. It takes about 2-3 seconds from each change of tab (Vargas, graphical dasa, astakavarga, sarvatobhadra). The vimsopaka bala, text window, yogas and shadbala views are snappy and fast. 

In comparison, Maitreya 7 is fast, it takes only milliseconds to go from tab to tab.

**Comment by martin-pe** [comment]
Bug is partially fixed now. Means that multiple vedic views are much faster now. That's why I close this issue.
Nevertheless there are some problems left:
- if symbols for planets are selected the performance decreases from time to time. Seems to be connected to problems with wxtheFontList.
- skins with rotated hue are still slow under UNIX/wxgtk3 (e.g. skin marble with colored signs). This is due to a workaround with background images in wxBrush.
